### ISSUE TITLE
Not so Merri~weather

### ISSUE THREAD

**Issue by drew0036** [drew0036/events-calendar#1]
Hey @muxlowc,

I'm not sure why Markbot is not accepting my google fonts link for Merriweather. I did the link embed on HTML and the font-family in CSS with no quotes. Any suggestions?

Thank you,
- Holly

**Comment by muxlowc** [comment]
@drew0036 
Try changing your linked font to the below:
  `<link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">`

(google fonts has updated since this assignment was made I think, so the above is a slightly order version)

hope that works!

**Comment by drew0036** [comment]
Got it, thank you!
